Repository projectceladon/kernelflinger, pull requests merged in 2023-11, with the labels that each got.

#105 Support booting from disk not on PCI bridge
  libkernelflinger/android.c
Labels: PR approved

#110 Disable print for the prebuilt kernelflinger.efi
  prebuilt/board/RPL_IVI/kernelflinger.efi
Labels: Valid commit message, PR approved

#112 pass ACRN cmdline parameter from sbl to os
  include/vars.h
  libkernelflinger/android.c
  libkernelflinger/vars.c
Labels: Valid commit message

#113 Fix size mismatch in snprintf for serialno, add a missing bit
  libkernelflinger/vars.c
Labels: Valid commit message, PR approved

#111 OP-TEE: send root of trust via ivshmem driver to optee
  include/security.h
  kernelflinger.c
  libkernelflinger/security.c
Labels: Valid commit message, PR approved
