Repository projectceladon/kernelflinger, pull requests merged in 2023-12, with the labels that each got.

#114 Rebase installer.efi to latest for blizzard
  prebuilt/board/RPL_IVI/blizzard_ivi/installer.efi
Labels: Valid commit message, PR approved

#115 Forward TPM requests to TEE via ivshmem
  include/ivshmem.h
  include/tpm2_security.h
  kernelflinger.c
  libkernelflinger/ivshmem.c
  libkernelflinger/tpm2_security.c
  prebuilt/board/RPL_IVI/installer.efi
  prebuilt/board/RPL_IVI/kernelflinger.efi
Labels: PR approved

#116 Remove bootloader partition hash calculation
  libfastboot/fastboot_oem.c
Labels: Valid commit message, PR approved

#117 Increase TPM pause value
  libedk2_tpm/Tpm2Ptp.c
  libedk2_tpm/Tpm2Tis.c
Labels: Valid commit message, PR approved

#119 KF: update attribute for tpm index
  libkernelflinger/tpm2_security.c
  prebuilt/board/RPL_IVI/installer.efi
  prebuilt/board/RPL_IVI/kernelflinger.efi
Labels: Valid commit message

#118 Add a memdump function without check for NULL source to pull whole ram
  include/lib.h
  libadb/adb_socket.c
  libkernelflinger/lib.c
Labels: Valid commit message, PR approved

#120 Revert "KF: update attribute for tpm index"
  libkernelflinger/tpm2_security.c
  prebuilt/board/RPL_IVI/installer.efi
  prebuilt/board/RPL_IVI/kernelflinger.efi
Labels: Valid commit message, PR approved
